package randomizer

import (
	"encoding/binary"
	"net"
)

// CIDRKind identifies the network prefix kind generated by [Network].
type CIDRKind uint8

const (
	// IPv4CIDR identifies a random IPv4 network with caller-selected prefix length.
	IPv4CIDR CIDRKind = iota
	// IPv6CIDR identifies a random IPv6 network with caller-selected prefix length.
	IPv6CIDR
	// IPv6ULAPrefix identifies an RFC 4193 unique-local IPv6 /48 prefix.
	IPv6ULAPrefix
)

type networkCIDR struct {
	ipNet net.IPNet
	data  [32]byte
}

// prefixLen clamps bits to the address length of kind and returns it with
// the address byte length.
func prefixLen(kind CIDRKind, bits uint8) (uint8, int) {
	switch kind {
	case IPv6CIDR:
		return min(bits, 128), net.IPv6len
	case IPv6ULAPrefix:
		return 48, net.IPv6len
	default:
		return min(bits, 32), net.IPv4len
	}
}

// fillPrefix writes a random network address of kind into ip with the host
// bits below bits cleared. len(ip) must match kind.
func fillPrefix(ip []byte, kind CIDRKind, bits uint8, p Provider) {
	if kind == IPv6ULAPrefix {
		x := p.Sum64()
		clear(ip)
		ip[0] = 0xfd
		ip[1], ip[2], ip[3], ip[4], ip[5] = byte(x), byte(x>>8), byte(x>>16), byte(x>>24), byte(x>>32)
		return
	}
	fillRandomBytes(ip, p)
	maskHostBits(ip, bits)
}

// maskHostBits clears every bit of ip after the first bits bits.
func maskHostBits(ip []byte, bits uint8) {
	full := int(bits >> 3)
	if rem := bits & 7; rem != 0 {
		ip[full] &= 0xff << (8 - rem)
		full++
	}
	clear(ip[full:])
}

func fillCIDRMask(mask []byte, bits uint8) {
	full := int(bits >> 3)
	for i := range full {
		mask[i] = 0xff
	}
	if rem := bits & 7; rem != 0 {
		mask[full] = 0xff << (8 - rem)
	}
}

// CIDR returns a random network prefix selected by kind.
// It clamps IPv4 prefix lengths to [0, 32] and IPv6 prefix lengths to [0, 128].
func (network) CIDR(kind CIDRKind, bits uint8) *net.IPNet {
	bits, n := prefixLen(kind, bits)
	buf := new(networkCIDR)
	ip := buf.data[:n:n]
	mask := buf.data[n : 2*n : 2*n]
	fillPrefix(ip, kind, bits, currentProvider())
	fillCIDRMask(mask, bits)
	buf.ipNet.IP = net.IP(ip)
	buf.ipNet.Mask = net.IPMask(mask)
	return &buf.ipNet
}

// IPInCIDR writes a random host address inside ipNet into dst and returns it.
// It returns nil when ipNet is nil or not a valid IPv4 or IPv6 network.
func (network) IPInCIDR(dst []byte, ipNet *net.IPNet) net.IP {
	if ipNet == nil {
		return nil
	}
	p := currentProvider()
	mask := ipNet.Mask
	switch len(mask) {
	case net.IPv4len:
		ip4 := ipNet.IP.To4()
		if ip4 == nil {
			return nil
		}
		b := fixedBytes(dst, net.IPv4len)
		putIPv4(b, hostBits32(binary.BigEndian.Uint32(ip4), binary.BigEndian.Uint32(mask), uint32(p.Sum64())))
		return net.IP(b)
	case net.IPv6len:
		ip6 := ipNet.IP.To16()
		if ip6 == nil {
			return nil
		}
		b := fixedBytes(dst, net.IPv6len)
		binary.BigEndian.PutUint64(b, hostBits64(binary.BigEndian.Uint64(ip6), binary.BigEndian.Uint64(mask), p.Sum64()))
		binary.BigEndian.PutUint64(b[8:], hostBits64(binary.BigEndian.Uint64(ip6[8:]), binary.BigEndian.Uint64(mask[8:]), p.Sum64()))
		return net.IP(b)
	default:
		return nil
	}
}

// hostBits32 keeps the masked network bits of base and takes the host bits
// from x.
func hostBits32(base, mask, x uint32) uint32 {
	return base&mask | x&^mask
}

// hostBits64 keeps the masked network bits of base and takes the host bits
// from x.
func hostBits64(base, mask, x uint64) uint64 {
	return base&mask | x&^mask
}
