package randomizer

import (
	"encoding/binary"
	"net"
)

type network struct{}

// Network provides random network addresses, identifiers, and port values
// using the active [Provider] selected by [SetProvider].
var Network network

func fixedBytes(dst []byte, n int) []byte {
	if cap(dst) < n {
		return make([]byte, n)
	}
	return dst[:n]
}

func fillRandomBytes(out []byte, provider Provider) {
	var (
		i int
		n = len(out)
	)
	for ; i+8 <= n; i += 8 {
		binary.LittleEndian.PutUint64(out[i:i+8], provider.Sum64())
	}
	if i < n {
		x := provider.Sum64()
		for j := i; j < n; j++ {
			out[j] = byte(x)
			x >>= 8
		}
	}
}

func putIPv4(b []byte, x uint32) {
	b[0], b[1], b[2], b[3] = byte(x>>24), byte(x>>16), byte(x>>8), byte(x)
}

// IPKind identifies the network address kind generated by [Network].
type IPKind uint8

const (
	// IPv4Any identifies a fully random 4-byte IPv4 address.
	IPv4Any IPKind = iota
	// IPv4Private identifies an RFC 1918 private IPv4 address.
	IPv4Private
	// IPv4LinkLocal identifies an RFC 3927 link-local IPv4 address in 169.254.0.0/16.
	IPv4LinkLocal
	// IPv4Multicast identifies an RFC 5771 multicast IPv4 address in 224.0.0.0/4.
	IPv4Multicast
	// IPv4Public identifies a globally-routable IPv4 address outside IANA special-purpose ranges.
	IPv4Public
	// IPv6Any identifies a fully random 16-byte IPv6 address.
	IPv6Any
	// IPv6Global identifies a global IPv6 unicast address in 2000::/3.
	IPv6Global
	// IPv6LinkLocal identifies a link-local IPv6 unicast address in fe80::/10.
	IPv6LinkLocal
	// IPv6SiteLocal identifies a site-local IPv6 unicast address in fec0::/10.
	IPv6SiteLocal
	// IPv6UniqueLocal identifies a unique-local IPv6 unicast address in fd00::/8.
	IPv6UniqueLocal
	// IPv6Private identifies a unique-local IPv6 unicast address in fd00::/8.
	IPv6Private IPKind = IPv6UniqueLocal
	// IPv6InterfaceLocalMulticast identifies IPv6 multicast scope 0x1.
	IPv6InterfaceLocalMulticast IPKind = iota
	// IPv6LinkLocalMulticast identifies IPv6 multicast scope 0x2.
	IPv6LinkLocalMulticast
	// IPv6AdminLocalMulticast identifies IPv6 multicast scope 0x4.
	IPv6AdminLocalMulticast
	// IPv6SiteLocalMulticast identifies IPv6 multicast scope 0x5.
	IPv6SiteLocalMulticast
	// IPv6OrgLocalMulticast identifies IPv6 multicast scope 0x8.
	IPv6OrgLocalMulticast
	// IPv6GlobalMulticast identifies IPv6 multicast scope 0xe.
	IPv6GlobalMulticast
)

// IP writes a random address selected by kind into dst and returns it.
// It allocates only when dst capacity is too small for the selected address.
func (network) IP(dst []byte, kind IPKind) net.IP {
	provider := currentProvider()
	switch kind {
	case IPv4Private:
		x := provider.Sum64()
		b := fixedBytes(dst, net.IPv4len)
		switch uniformUint64n(3, provider) {
		case 0:
			b[0] = 10
			b[1] = byte(x >> 8)
			b[2] = byte(x >> 16)
			b[3] = byte(x >> 24)
		case 1:
			b[0] = 172
			b[1] = 16 + (byte(x>>8) & 0x0f)
			b[2] = byte(x >> 16)
			b[3] = byte(x >> 24)
		default:
			b[0] = 192
			b[1] = 168
			b[2] = byte(x >> 16)
			b[3] = byte(x >> 24)
		}
		return net.IP(b)
	case IPv4LinkLocal:
		x := uint32(provider.Sum64())
		b := fixedBytes(dst, net.IPv4len)
		b[0], b[1], b[2], b[3] = 169, 254, byte(x), byte(x>>8)
		return net.IP(b)
	case IPv4Multicast:
		x := uint32(provider.Sum64())
		b := fixedBytes(dst, net.IPv4len)
		b[0] = 0xe0 | (byte(x) & 0x0f)
		b[1], b[2], b[3] = byte(x>>8), byte(x>>16), byte(x>>24)
		return net.IP(b)
	case IPv4Public:
		var x uint32
		for {
			x = uint32(provider.Sum64())
			if isPublicIPv4(x) {
				break
			}
		}
		b := fixedBytes(dst, net.IPv4len)
		putIPv4(b, x)
		return net.IP(b)
	case IPv6Any, IPv6Global, IPv6LinkLocal, IPv6SiteLocal, IPv6UniqueLocal,
		IPv6InterfaceLocalMulticast, IPv6LinkLocalMulticast, IPv6AdminLocalMulticast,
		IPv6SiteLocalMulticast, IPv6OrgLocalMulticast, IPv6GlobalMulticast:
		b := fixedBytes(dst, net.IPv6len)
		fillRandomBytes(b, provider)
		if kind >= IPv6InterfaceLocalMulticast {
			b[0] = 0xff
		}
		switch kind {
		case IPv6Global:
			b[0] = (b[0] & 0x1f) | 0x20
		case IPv6LinkLocal:
			b[0] = 0xfe
			b[1] = (b[1] & 0x3f) | 0x80
		case IPv6SiteLocal:
			b[0] = 0xfe
			b[1] = (b[1] & 0x3f) | 0xc0
		case IPv6UniqueLocal:
			b[0] = 0xfd
		case IPv6InterfaceLocalMulticast:
			b[1] = 0x1
		case IPv6LinkLocalMulticast:
			b[1] = 0x2
		case IPv6AdminLocalMulticast:
			b[1] = 0x4
		case IPv6SiteLocalMulticast:
			b[1] = 0x5
		case IPv6OrgLocalMulticast:
			b[1] = 0x8
		case IPv6GlobalMulticast:
			b[1] = 0xe
		}
		return net.IP(b)
	default:
		b := fixedBytes(dst, net.IPv4len)
		putIPv4(b, uint32(provider.Sum64()))
		return net.IP(b)
	}
}

// isPublicIPv4 reports whether x, interpreted big-endian, lies outside every
// IANA special-purpose, private, and bogon IPv4 range. See RFC 6890.
func isPublicIPv4(x uint32) bool {
	a, b, c := byte(x>>24), byte(x>>16), byte(x>>8)
	switch {
	case a == 0, a == 10, a == 127:
		return false
	case a == 100 && b&0xc0 == 64: // 100.64.0.0/10 (CGN)
		return false
	case a == 169 && b == 254: // 169.254.0.0/16
		return false
	case a == 172 && b&0xf0 == 16: // 172.16.0.0/12
		return false
	case a == 192 && b == 0 && c == 0: // 192.0.0.0/24
		return false
	case a == 192 && b == 0 && c == 2: // 192.0.2.0/24 (TEST-NET-1)
		return false
	case a == 192 && b == 88 && c == 99: // 192.88.99.0/24
		return false
	case a == 192 && b == 168: // 192.168.0.0/16
		return false
	case a == 198 && b&0xfe == 18: // 198.18.0.0/15
		return false
	case a == 198 && b == 51 && c == 100: // 198.51.100.0/24 (TEST-NET-2)
		return false
	case a == 203 && b == 0 && c == 113: // 203.0.113.0/24 (TEST-NET-3)
		return false
	case a >= 224: // 224.0.0.0/4 multicast + 240.0.0.0/4 reserved
		return false
	}
	return true
}

// HardwareKind identifies the link-layer address kind generated by [Network].
type HardwareKind uint8

const (
	// HardwareMAC identifies a random 6-byte MAC address.
	HardwareMAC HardwareKind = iota
	// HardwareMACOUI identifies a random MAC address with caller-supplied OUI bytes.
	HardwareMACOUI
	// HardwareMACRealOUI identifies a random MAC address with a built-in real OUI.
	HardwareMACRealOUI
	// HardwareEUI64 identifies a random locally-administered unicast EUI-64 identifier.
	HardwareEUI64
	// HardwareEUI64FromMAC identifies an EUI-64 identifier derived from a 6-byte MAC address.
	HardwareEUI64FromMAC
)

// HardwareOptions configures link-layer address generation through [Network].
type HardwareOptions struct {
	// OUI supplies the prefix for [HardwareMACOUI].
	OUI [3]byte
	// MAC supplies source bytes for [HardwareEUI64FromMAC].
	MAC net.HardwareAddr
	// Local controls the U/L bit for [HardwareMAC].
	Local bool
	// Multicast controls the I/G bit for [HardwareMAC].
	Multicast bool
}

// realOUIs are registered universal-unicast IEEE OUI prefixes from well-known
// NIC vendors.
var realOUIs = [...][3]byte{
	{0x3c, 0x22, 0xfb}, // Apple
	{0x00, 0x1a, 0xa0}, // Dell
	{0x00, 0x25, 0x9c}, // Cisco
	{0x00, 0x1b, 0x21}, // Intel
	{0x00, 0x16, 0x32}, // Samsung
	{0xb8, 0x27, 0xeb}, // Raspberry Pi
	{0x00, 0x50, 0x56}, // VMware
	{0x00, 0x15, 0x5d}, // Microsoft (Hyper-V)
	{0xf0, 0x9f, 0xc2}, // Ubiquiti
	{0x50, 0xc7, 0xbf}, // TP-Link
}

// Hardware writes a link-layer address selected by kind into dst and returns it.
// It returns nil for [HardwareEUI64FromMAC] when options.MAC is not 6 bytes.
func (network) Hardware(dst []byte, kind HardwareKind, options HardwareOptions) net.HardwareAddr {
	provider := currentProvider()
	switch kind {
	case HardwareMACOUI:
		x := uint32(provider.Sum64())
		b := fixedBytes(dst, 6)
		b[0], b[1], b[2] = options.OUI[0], options.OUI[1], options.OUI[2]
		b[3], b[4], b[5] = byte(x), byte(x>>8), byte(x>>16)
		return net.HardwareAddr(b)
	case HardwareMACRealOUI:
		x := provider.Sum64()
		oui := realOUIs[x%uint64(len(realOUIs))]
		b := fixedBytes(dst, 6)
		b[0], b[1], b[2] = oui[0], oui[1], oui[2]
		b[3], b[4], b[5] = byte(x>>24), byte(x>>32), byte(x>>40)
		return net.HardwareAddr(b)
	case HardwareEUI64:
		b := fixedBytes(dst, 8)
		binary.LittleEndian.PutUint64(b, provider.Sum64())
		b[0] |= 0x02
		b[0] &^= 0x01
		return net.HardwareAddr(b)
	case HardwareEUI64FromMAC:
		mac := options.MAC
		if len(mac) != 6 {
			return nil
		}
		b := fixedBytes(dst, 8)
		b[0] = mac[0] ^ 0x02
		b[1] = mac[1]
		b[2] = mac[2]
		b[3] = 0xff
		b[4] = 0xfe
		b[5] = mac[3]
		b[6] = mac[4]
		b[7] = mac[5]
		return net.HardwareAddr(b)
	default:
		b := fixedBytes(dst, 6)
		fillRandomBytes(b, provider)
		b[0] &^= 0x03
		if options.Local {
			b[0] |= 0x02
		}
		if options.Multicast {
			b[0] |= 0x01
		}
		return net.HardwareAddr(b)
	}
}

// ValueKind identifies a random network numeric value generated by [Network].
type ValueKind uint8

const (
	// AnyPort identifies the full port value range [0, 65535].
	AnyPort ValueKind = iota
	// PrivilegedPort identifies the IANA well-known port range [1, 1023].
	PrivilegedPort
	// RegisteredPort identifies the IANA registered port range [1024, 49151].
	RegisteredPort
	// EphemeralPort identifies the dynamic and private port range [49152, 65535].
	EphemeralPort
	// VLANID identifies a 12-bit IEEE 802.1Q VLAN ID in [0, 4095].
	VLANID
	// ASN identifies a 32-bit Autonomous System Number in [0, 4294967295].
	ASN
	// VNI identifies a 24-bit VXLAN Network Identifier in [0, 16777215].
	VNI
	// FlowLabel identifies a 20-bit IPv6 flow label in [0, 1048575].
	FlowLabel
	// MPLSLabel identifies a 20-bit MPLS label in [0, 1048575].
	MPLSLabel
	// IPv6InterfaceID identifies a 64-bit IPv6 interface identifier with U/L and I/G bits clear.
	IPv6InterfaceID
)

// Value returns a random integer selected by kind.
func (network) Value(kind ValueKind) uint64 {
	provider := currentProvider()
	switch kind {
	case PrivilegedPort:
		return uniformUint64n(1023, provider) + 1
	case RegisteredPort:
		return uniformUint64n(48128, provider) + 1024
	case EphemeralPort:
		return uint64(uint16(provider.Sum64()>>50) + 49152)
	case VLANID:
		return provider.Sum64() >> 52
	case ASN:
		return provider.Sum64() >> 32
	case VNI:
		return provider.Sum64() >> 40
	case FlowLabel, MPLSLabel:
		return provider.Sum64() >> 44
	case IPv6InterfaceID:
		return provider.Sum64() &^ (uint64(0x03) << 56)
	default:
		return provider.Sum64() >> 48
	}
}

// CIDRKind identifies the network prefix kind generated by [Network].
type CIDRKind uint8

const (
	// IPv4CIDR identifies a random IPv4 network with caller-selected prefix length.
	IPv4CIDR CIDRKind = iota
	// IPv6CIDR identifies a random IPv6 network with caller-selected prefix length.
	IPv6CIDR
	// IPv6ULAPrefix identifies an RFC 4193 unique-local IPv6 /48 prefix.
	IPv6ULAPrefix
)

type networkCIDR struct {
	ipNet net.IPNet
	data  [32]byte
}

func fillCIDRMask(mask []byte, prefixLen uint8) {
	full := int(prefixLen >> 3)
	for i := range full {
		mask[i] = 0xff
	}
	if rem := prefixLen & 7; rem != 0 {
		mask[full] = 0xff << (8 - rem)
	}
}

// CIDR returns a random network prefix selected by kind.
// It clamps IPv4 prefix lengths to [0, 32] and IPv6 prefix lengths to [0, 128].
func (network) CIDR(kind CIDRKind, prefixLen uint8) *net.IPNet {
	buf := new(networkCIDR)
	provider := currentProvider()
	switch kind {
	case IPv6CIDR:
		if prefixLen > 128 {
			prefixLen = 128
		}
		ip := buf.data[:16:16]
		mask := buf.data[16:32:32]
		fillRandomBytes(ip, provider)
		fillCIDRMask(mask, prefixLen)
		for i := range ip {
			ip[i] &= mask[i]
		}
		buf.ipNet.IP = net.IP(ip)
		buf.ipNet.Mask = net.IPMask(mask)
	case IPv6ULAPrefix:
		ip := buf.data[:16:16]
		mask := buf.data[16:32:32]
		x := provider.Sum64()
		ip[0] = 0xfd
		ip[1] = byte(x)
		ip[2] = byte(x >> 8)
		ip[3] = byte(x >> 16)
		ip[4] = byte(x >> 24)
		ip[5] = byte(x >> 32)
		fillCIDRMask(mask, 48)
		buf.ipNet.IP = net.IP(ip)
		buf.ipNet.Mask = net.IPMask(mask)
	default:
		if prefixLen > 32 {
			prefixLen = 32
		}
		ip := buf.data[:4:4]
		mask := buf.data[4:8:8]
		putIPv4(ip, uint32(provider.Sum64()))
		fillCIDRMask(mask, prefixLen)
		for i := range ip {
			ip[i] &= mask[i]
		}
		buf.ipNet.IP = net.IP(ip)
		buf.ipNet.Mask = net.IPMask(mask)
	}
	return &buf.ipNet
}

// IPInCIDR writes a random host address inside ipNet into dst and returns it.
// It returns nil when ipNet is nil or not a valid IPv4 or IPv6 network.
func (network) IPInCIDR(dst []byte, ipNet *net.IPNet) net.IP {
	if ipNet == nil {
		return nil
	}
	var (
		provider = currentProvider()
		mask     = ipNet.Mask
	)
	switch len(mask) {
	case net.IPv4len:
		ip4 := ipNet.IP.To4()
		if ip4 == nil {
			return nil
		}
		x := uint32(provider.Sum64())
		b := fixedBytes(dst, net.IPv4len)
		b[0] = ip4[0] | (byte(x>>24) &^ mask[0])
		b[1] = ip4[1] | (byte(x>>16) &^ mask[1])
		b[2] = ip4[2] | (byte(x>>8) &^ mask[2])
		b[3] = ip4[3] | (byte(x) &^ mask[3])
		return net.IP(b)
	case net.IPv6len:
		ip6 := ipNet.IP.To16()
		if ip6 == nil {
			return nil
		}
		var (
			b  = fixedBytes(dst, net.IPv6len)
			x0 = provider.Sum64()
			x1 = provider.Sum64()
		)
		for i := range 8 {
			b[i] = ip6[i] | (byte(x0>>(uint(i)<<3)) &^ mask[i])
		}
		for i := 8; i < 16; i++ {
			b[i] = ip6[i] | (byte(x1>>(uint(i-8)<<3)) &^ mask[i])
		}
		return net.IP(b)
	default:
		return nil
	}
}

// UUID returns a random RFC 4122 version-4 UUID as a [16]byte value.
func (network) UUID() [16]byte {
	var b [16]byte
	provider := currentProvider()
	binary.LittleEndian.PutUint64(b[:8], provider.Sum64())
	binary.LittleEndian.PutUint64(b[8:], provider.Sum64())
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return b
}

// uuidHexEncode encodes src into dst as lowercase hex pairs.
func uuidHexEncode(dst []byte, src []byte) {
	for i, v := range src {
		dst[i<<1] = lhexdict[v>>4]
		dst[i<<1|1] = lhexdict[v&0x0f]
	}
}

// AppendUUID appends a random RFC 4122 version-4 UUID in standard lowercase
// text form to dst and returns the extended slice.
func (n network) AppendUUID(dst []byte) []byte {
	const uuidTemplate = "00000000-0000-0000-0000-000000000000"
	uuid := n.UUID()
	offset := len(dst)
	dst = append(dst, uuidTemplate...)
	b := dst[offset:]
	uuidHexEncode(b[0:8], uuid[0:4])
	uuidHexEncode(b[9:13], uuid[4:6])
	uuidHexEncode(b[14:18], uuid[6:8])
	uuidHexEncode(b[19:23], uuid[8:10])
	uuidHexEncode(b[24:36], uuid[10:16])
	return dst
}
