package randomizer

import (
	"slices"
	"unsafe"
)

type telecom struct{}

// Telecom provides random mobile equipment and subscriber identifiers using
// the active [Provider] selected by [SetProvider].
var Telecom telecom

// TelecomKind identifies the identifier generated by [Telecom].
type TelecomKind uint8

const (
	// IMEI identifies a 15-digit International Mobile Equipment Identity per
	// GSMA TS.06: an 8-digit Type Allocation Code, a 6-digit serial number,
	// and a Luhn check digit.
	IMEI TelecomKind = iota
	// IMEISV identifies a 16-digit IMEI Software Version: the 14 IMEI digits
	// without the check digit followed by a 2-digit software version number
	// in [00, 98], since 3GPP TS 23.003 reserves 99.
	IMEISV
	// ICCID identifies an ITU-T E.118 Integrated Circuit Card Identifier: the
	// major industry identifier 89, an E.164 country code, issuer and account
	// digits, and a Luhn check digit, 19 digits in total by default.
	ICCID
	// MEID identifies a 14-digit hexadecimal 3GPP2 Mobile Equipment
	// Identifier with a regional code in [A0, FF].
	MEID
)

// TelecomOptions configures identifier generation through [Telecom]. Fields
// left empty are generated randomly; an invalid field makes generation fail.
type TelecomOptions struct {
	// TAC is the 8-digit Type Allocation Code for [IMEI] and [IMEISV].
	TAC string
	// SVN is the 2-digit software version for [IMEISV], other than 99.
	SVN string
	// IIN is the issuer identifier prefix for [ICCID]: 89 followed by 1 to 5
	// further digits.
	IIN string
	// Length is the total digit count for [ICCID]: 0 selects 19; 18 to 20 are accepted.
	Length int
	// Test selects the GSMA test range for [IMEI] and [IMEISV] by using
	// Reporting Body Identifier 00 when TAC is empty.
	Test bool
}

// reportingBodyIDs are the two-digit Reporting Body Identifiers that lead a
// Type Allocation Code: the active bodies 01 (CTIA), 35 (BABT), and 86 (TAF)
// plus legacy allocators still present in the field. 00 is the test range
// and 99 is reserved for the Global Hexadecimal Administrator.
var reportingBodyIDs = [...]string{"01", "35", "86", "33", "44", "45", "49", "50", "51", "52", "53", "54", "91", "98"}

// countryCodes are assigned ITU-T E.164 country calling codes used to form
// the issuer identifier of an [ICCID].
var countryCodes = [...]string{
	"1", "7", "20", "27", "30", "31", "32", "33", "34", "36", "39", "40", "41",
	"43", "44", "45", "46", "47", "48", "49", "51", "52", "53", "54", "55", "56",
	"57", "58", "60", "61", "62", "63", "64", "65", "66", "81", "82", "84", "86",
	"90", "91", "92", "93", "94", "95", "98", "212", "213", "216", "218", "234",
	"254", "351", "352", "353", "354", "358", "359", "370", "371", "372", "380",
	"381", "385", "386", "420", "421", "852", "853", "855", "856", "880", "886",
	"960", "961", "962", "963", "964", "965", "966", "967", "968", "971", "972",
	"973", "974", "975", "976", "977", "992", "993", "994", "995", "996", "998",
}

// String returns a random identifier selected by kind, or an empty string
// when options are invalid.
func (t telecom) String(kind TelecomKind, options TelecomOptions) string {
	out := t.Append(nil, kind, options)
	if len(out) == 0 {
		return ""
	}
	return unsafe.String(unsafe.SliceData(out), len(out))
}

// Append appends a random identifier selected by kind to dst and returns the
// extended slice. It allocates only when dst lacks capacity and returns dst
// unchanged when options are invalid.
func (telecom) Append(dst []byte, kind TelecomKind, options TelecomOptions) []byte {
	p := currentProvider()
	switch kind {
	case IMEISV:
		if !isDigits(options.SVN, 2, 2) || options.SVN == "99" {
			if options.SVN != "" {
				return dst
			}
		}
		out, ok := appendTAC(slices.Grow(dst, 16), options, p)
		if !ok {
			return dst
		}
		out = appendRandomDigits(out, 6, p)
		if options.SVN != "" {
			return append(out, options.SVN...)
		}
		return appendTwoDigits(out, byte(boundedFrom(p.Sum64(), 99, p)))
	case ICCID:
		length := options.Length
		if length == 0 {
			length = 19
		}
		if length < 18 || length > 20 {
			return dst
		}
		if options.IIN != "" && (!isDigits(options.IIN, 3, 7) || options.IIN[0] != '8' || options.IIN[1] != '9') {
			return dst
		}
		offset := len(dst)
		out := slices.Grow(dst, length)
		if options.IIN != "" {
			out = append(out, options.IIN...)
		} else {
			out = append(out, '8', '9')
			out = append(out, countryCodes[boundedFrom(p.Sum64(), uint64(len(countryCodes)), p)]...)
		}
		out = appendRandomDigits(out, offset+length-1-len(out), p)
		return append(out, luhnCheckDigit(out[offset:]))
	case MEID:
		x := p.Sum64()
		out := slices.Grow(dst, 14)
		rr := byte(boundedFrom(x, 0x60, p)) + 0xa0
		out = append(out, uhexdict[rr>>4], uhexdict[rr&0x0f])
		for i := range 12 {
			out = append(out, uhexdict[(x>>(i*4))&0x0f])
		}
		return out
	default:
		offset := len(dst)
		out, ok := appendTAC(slices.Grow(dst, 15), options, p)
		if !ok {
			return dst
		}
		out = appendRandomDigits(out, 6, p)
		return append(out, luhnCheckDigit(out[offset:]))
	}
}

// appendTAC appends the 8-digit Type Allocation Code from options, or a
// random one led by a Reporting Body Identifier, and reports whether options
// were valid.
func appendTAC(dst []byte, options TelecomOptions, p Provider) ([]byte, bool) {
	if options.TAC != "" {
		if !isDigits(options.TAC, 8, 8) {
			return dst, false
		}
		return append(dst, options.TAC...), true
	}
	if options.Test {
		dst = append(dst, '0', '0')
	} else {
		dst = append(dst, reportingBodyIDs[boundedFrom(p.Sum64(), uint64(len(reportingBodyIDs)), p)]...)
	}
	return appendRandomDigits(dst, 6, p), true
}

// isDigits reports whether s consists of minLen to maxLen ASCII digits.
func isDigits(s string, minLen, maxLen int) bool {
	if len(s) < minLen || len(s) > maxLen {
		return false
	}
	for i := 0; i < len(s); i++ {
		if s[i] < '0' || s[i] > '9' {
			return false
		}
	}
	return true
}

func appendTwoDigits(dst []byte, v byte) []byte {
	return append(dst, '0'+v/10, '0'+v%10)
}

// appendRandomDigits appends n uniform decimal digits to dst, taking up to
// eighteen digits from each random word: words of 18e18 and above are
// rejected (probability 2.4%) so the remainder modulo 1e18 is exact.
func appendRandomDigits(dst []byte, n int, p Provider) []byte {
	for n > 0 {
		x := p.Sum64()
		for x >= 18_000_000_000_000_000_000 {
			x = p.Sum64()
		}
		x %= 1_000_000_000_000_000_000
		take := min(n, 18)
		offset := len(dst)
		dst = append(dst, "000000000000000000"[:take]...)
		for i := offset + take - 1; i >= offset; i-- {
			dst[i] = '0' + byte(x%10)
			x /= 10
		}
		n -= take
	}
	return dst
}

// luhnCheckDigit returns the ISO/IEC 7812 Luhn check digit for the ASCII
// digits in payload.
func luhnCheckDigit(payload []byte) byte {
	sum := 0
	double := true
	for i := len(payload) - 1; i >= 0; i-- {
		v := int(payload[i] - '0')
		if double {
			v *= 2
			if v > 9 {
				v -= 9
			}
		}
		sum += v
		double = !double
	}
	return '0' + byte((10-sum%10)%10)
}
