package randomizer

// ValueKind identifies a random network numeric value generated by [Network].
type ValueKind uint8

const (
	// AnyPort identifies the full port value range [0, 65535].
	AnyPort ValueKind = iota
	// PrivilegedPort identifies the IANA well-known port range [1, 1023].
	PrivilegedPort
	// RegisteredPort identifies the IANA registered port range [1024, 49151].
	RegisteredPort
	// EphemeralPort identifies the dynamic and private port range [49152, 65535].
	EphemeralPort
	// VLANID identifies a 12-bit IEEE 802.1Q VLAN ID in [0, 4095].
	VLANID
	// ASN identifies a 32-bit Autonomous System Number in [0, 4294967295].
	ASN
	// VNI identifies a 24-bit VXLAN Network Identifier in [0, 16777215].
	VNI
	// FlowLabel identifies a 20-bit IPv6 flow label in [0, 1048575].
	FlowLabel
	// MPLSLabel identifies a 20-bit MPLS label in [0, 1048575].
	MPLSLabel
	// IPv6InterfaceID identifies a 64-bit IPv6 interface identifier with U/L and I/G bits clear.
	IPv6InterfaceID
	// VLANIDUnreserved identifies an assignable IEEE 802.1Q VLAN ID in
	// [1, 4094]; 0 marks priority-tagged frames and 4095 is reserved.
	VLANIDUnreserved
	// MPLSLabelUnreserved identifies an MPLS label in [16, 1048575], outside
	// the RFC 7274 special-purpose labels 0-15.
	MPLSLabelUnreserved
	// ASNPublic identifies a 32-bit Autonomous System Number that IANA can
	// assign: it excludes 0 (RFC 7607), 23456 (AS_TRANS, RFC 6793),
	// 64496-131071 (RFC 5398 documentation, RFC 6996 private, RFC 7300 last
	// 16-bit, and IANA reserved), and 4200000000-4294967295 (RFC 6996
	// private and RFC 7300 last 32-bit).
	ASNPublic
	// ASNPublic16 identifies an assignable 16-bit Autonomous System Number in
	// [1, 64495] other than 23456.
	ASNPublic16
	// ASNPrivate16 identifies an RFC 6996 private 16-bit Autonomous System
	// Number in [64512, 65534].
	ASNPrivate16
	// ASNPrivate32 identifies an RFC 6996 private 32-bit Autonomous System
	// Number in [4200000000, 4294967294].
	ASNPrivate32
)

// Value returns a random integer selected by kind. Unknown kinds produce [AnyPort].
func (network) Value(kind ValueKind) uint64 {
	p := currentProvider()
	x := p.Sum64()
	switch kind {
	case PrivilegedPort:
		return boundedFrom(x, 1023, p) + 1
	case RegisteredPort:
		return boundedFrom(x, 48128, p) + 1024
	case EphemeralPort:
		return uint64(uint16(x>>50) + 49152)
	case VLANID:
		return x >> 52
	case ASN:
		return x >> 32
	case VNI:
		return x >> 40
	case FlowLabel, MPLSLabel:
		return x >> 44
	case IPv6InterfaceID:
		return x &^ (uint64(0x03) << 56)
	case VLANIDUnreserved:
		return boundedFrom(x, 4094, p) + 1
	case MPLSLabelUnreserved:
		return boundedFrom(x, 1<<20-16, p) + 16
	case ASNPublic:
		for {
			if a := uint32(x); isPublicASN(a) {
				return uint64(a)
			}
			if a := uint32(x >> 32); isPublicASN(a) {
				return uint64(a)
			}
			x = p.Sum64()
		}
	case ASNPublic16:
		v := boundedFrom(x, 64494, p) + 1
		if v >= 23456 {
			v++
		}
		return v
	case ASNPrivate16:
		return boundedFrom(x, 1023, p) + 64512
	case ASNPrivate32:
		return boundedFrom(x, 94967295, p) + 4200000000
	default:
		return x >> 48
	}
}

// isPublicASN reports whether a is an Autonomous System Number outside every
// IANA reserved, private, and documentation range.
func isPublicASN(a uint32) bool {
	switch {
	case a == 0, a == 23456:
		return false
	case a >= 64496 && a <= 131071:
		return false
	case a >= 4200000000:
		return false
	}
	return true
}
